#!/usr/bin/env python3

import pathlib
import sys

# Force the search path to find the local regio library.
sys.path.insert(1, str(pathlib.Path(__file__).parent / 'src'))
from regio.tools.info import main

if __name__ == '__main__':
    sys.exit(main())
