#!/usr/bin/env python3

import pathlib
import sys

# Force the search path to find the local regio library.
base_dir = pathlib.Path(__file__).parent
sys.path.insert(1, str(base_dir / 'src'))
from regio.tools.elaborate import main

if __name__ == '__main__':
    sys.exit(main(str(base_dir)))
